// Mentors
import alan from "../../../assets/img/team/mentors/original/alan.png";
import jacob from "../../../assets/img/team/mentors/original/jacob.png";
import lakshmi from "../../../assets/img/team/mentors/original/lakshmi.png";
import neeraj from "../../../assets/img/team/mentors/original/neeraj.png";
import alanT from "../../../assets/img/team/mentors/alan.png";
import jacobT from "../../../assets/img/team/mentors/jacob.png";
import lakshmiT from "../../../assets/img/team/mentors/lakshmi.png";
import neerajT from "../../../assets/img/team/mentors/neeraj.png";

// Content Team
import anusree from "../../../assets/img/team/content/original/anusree.png";
import eby from "../../../assets/img/team/content/original/eby.png";
import fathima from "../../../assets/img/team/content/original/fathima.png";
import neha from "../../../assets/img/team/content/original/neha.png";
import rojin from "../../../assets/img/team/content/original/rojin.png";
import anusreeT from "../../../assets/img/team/content/anusree.png";
import ebyT from "../../../assets/img/team/content/eby.png";
import fathimaT from "../../../assets/img/team/content/fathima.png";
import nehaT from "../../../assets/img/team/content/neha.png";
import rojinT from "../../../assets/img/team/content/rojin.png";

// Design Team
import devanand from "../../../assets/img/team/design/original/devanand.png";
import divya from "../../../assets/img/team/design/original/divya.png";
import juliya from "../../../assets/img/team/design/original/juliya.png";
import sreerag from "../../../assets/img/team/design/original/sreerag.png";
import rema from "../../../assets/img/team/design/original/rema.png";
import devanandT from "../../../assets/img/team/design/devanand.png";
import divyaT from "../../../assets/img/team/design/divya.png";
import juliyaT from "../../../assets/img/team/design/juliya.png";
import sreeragT from "../../../assets/img/team/design/sreerag.png";
import remaT from "../../../assets/img/team/design/rema.png";

// Web Team
import abhijith from "../../../assets/img/team/web/original/abhijith.jpeg";
import gautham from "../../../assets/img/team/web/original/gautham.jpeg";
import arshad from "../../../assets/img/team/web/original/arshad.jpeg";
import aleena from "../../../assets/img/team/web/original/aleena.jpeg";
import akhil from "../../../assets/img/team/web/original/akhil.jpeg";
import gokul from "../../../assets/img/team/web/original/gokul.png";
import abhijithT from "../../../assets/img/team/web/abhijith.jpeg";
import gauthamT from "../../../assets/img/team/web/gautham.jpeg";
import arshadT from "../../../assets/img/team/web/arshad.jpeg";
import aleenaT from "../../../assets/img/team/web/aleena.jpeg";
import akhilT from "../../../assets/img/team/web/akhil.jpeg";
import gokulT from "../../../assets/img/team/web/gokul.png";

export const TeamDescription = {
  mentors: {
    title: "Mentoring Team",
    desc: "The Mentoring Team of four provides continuous support and guidance to our volunteers. They promote diversity of thought, tap into their existing knowledge, and direct the interns to a brighter future.",
  },
  content: {
    title: "Content Team",
    desc: "The Content Team of five interns is responsible for all the creative content generated by the Section, in the form of social media content, reports, proposals, etc. The team is mentored by Ms. Lekshmi Priya.",
  },
  design: {
    title: "Design Team",
    desc: "The Design Team of five interns executes all the designing works related to the Section, which include posters, flyers, etc. The team is mentored by Mr. Jacob Thomas, Treasurer, IEEE Kerala Young Professionals.",
  },
  web: {
    title: "Web Team",
    desc: "The Web Team of six interns handles the tasks related to IEEE Kerala Section’s official website, ieeekerala.org, and other such web-related activities of the Section. The team is mentored by Mr. Neeraj Ipe, Vice-Chair, IEEE Kerala Young Professionals.",
  },
};

export const MentorsData = [
  {
    id: 1,
    imgUrl: alan,
    toonImgUrl: alanT,
    name: "Alan Mathew ",
    descr: "ECC - IEEE Kerala Section",
    linkedin: "https://www.linkedin.com/in/alan-mathew-a452b3bb",
  },
  {
    id: 2,
    imgUrl: jacob,
    toonImgUrl: jacobT,
    name: "Jacob Thomas ",
    descr: "Treasurer - IEEE Kerala YP",
    linkedin: "https://www.linkedin.com/in/jacob-thomas-puthukeril",
  },
  {
    id: 3,
    imgUrl: neeraj,
    toonImgUrl: neerajT,
    name: "Neeraj Ipe ",
    descr: "Vice Chair - IEEE Kerala YP",
    linkedin: "https://www.linkedin.com/in/neeraj-ipe-23914261",
  },
  {
    id: 4,
    imgUrl: lakshmi,
    toonImgUrl: lakshmiT,
    name: "Lekshmi Priya ",
    descr: "Member - IEEE Kerala YP",
    linkedin: "https://www.linkedin.com/in/lekshmi-priya-b-9a6bb7136",
  },
];

export const ContentTeamData = [
  {
    id: 1,
    imgUrl: anusree,
    toonImgUrl: anusreeT,
    name: "Anushri P ",
    descr: "GEC Thrissur",
    linkedin: "https://www.linkedin.com/in/anushri-p-a0a624207",
  },
  {
    id: 2,
    imgUrl: fathima,
    toonImgUrl: fathimaT,
    name: "Fathima Nazreen ",
    descr: "LBSITW Trivandrum",
    linkedin: "https://www.linkedin.com/in/fathima-nazreen-43a894180",
  },
  {
    id: 3,
    imgUrl: neha,
    toonImgUrl: nehaT,
    name: "Neha Baju ",
    descr: "VAST Thrissur",
    linkedin: "https:https://www.linkedin.com/in/neha-baju-b6aa3b205",
  },
  {
    id: 4,
    imgUrl: rojin,
    toonImgUrl: rojinT,
    name: "Rojin K Sunny ",
    descr: "CE Chengannur",
    linkedin: "https://www.linkedin.com/in/rojinksunny",
  },
  {
    id: 5,
    imgUrl: eby,
    toonImgUrl: ebyT,
    name: "Eby Kurian TA ",
    descr: "FISAT Angamaly",
    linkedin: "https://www.linkedin.com/in/eby-kurian-3b53a9146",
  },
];

export const DesignTeamData = [
  {
    id: 1,
    imgUrl: devanand,
    toonImgUrl: devanandT,
    name: "Devanand A ",
    descr: "GECB Trivandrum",
    linkedin: "https://www.linkedin.com/in/1devanand",
  },
  {
    id: 2,
    imgUrl: divya,
    toonImgUrl: divyaT,
    name: "Divya Anu Kurian ",
    descr: "MITS Kochi",
    linkedin: "https://www.linkedin.com/in/divya-anu-a484aa205",
  },
  {
    id: 3,
    imgUrl: juliya,
    toonImgUrl: juliyaT,
    name: "Juliya Franics ",
    descr: "MITS Kochi",
    linkedin: "https://www.linkedin.com/in/juliya-francis-8b24711bb",
  },
  {
    id: 4,
    imgUrl: sreerag,
    toonImgUrl: sreeragT,
    name: "Sreerag N ",
    descr: "CE Chengannur",
    linkedin: "https://www.linkedin.com/in/sreerag-n-b50457190",
  },
  {
    id: 5,
    imgUrl: rema,
    toonImgUrl: remaT,
    name: "Remajothi S ",
    descr: "LBSTW Trivandrum",
    linkedin: "https://www.linkedin.com/in/remajothi-s-505b4a1b3",
  },
];

export const WebTeamData = [
  {
    id: 1,
    imgUrl: abhijith,
    toonImgUrl: abhijithT,
    name: "Abhijith Kannan ",
    descr: "CE Kidangoor",
    linkedin: "https://www.linkedin.com/in/abhijithkannan",
  },
  {
    id: 2,
    imgUrl: gautham,
    toonImgUrl: gauthamT,
    name: "Gautham P R ",
    descr: "SCT Trivandrum",
    linkedin: "https://www.linkedin.com/in/gautham-p-r-2a6039206",
  },
  {
    id: 3,
    imgUrl: arshad,
    toonImgUrl: arshadT,
    name: "Arshad Danish ",
    descr: "GCE Kannur",
    linkedin: "https://www.linkedin.com/in/arshaddanish",
  },
  {
    id: 4,
    imgUrl: aleena,
    toonImgUrl: aleenaT,
    name: "Aleena Anna Robin ",
    descr: "MITS Kochi",
    linkedin: "https://www.linkedin.com/in/aleena-anna-8453901b7",
  },
  {
    id: 5,
    imgUrl: akhil,
    toonImgUrl: akhilT,
    name: "Akhil Krishna U ",
    descr: "MCE Trivandrum",
    linkedin: "https://www.linkedin.com/in/akhil-krishna-u-855b47198",
  },
  {
    id: 5,
    imgUrl: gokul,
    toonImgUrl: gokulT,
    name: "Gokul C M ",
    descr: "GECB Trivandrum",
    linkedin: "https://www.linkedin.com/in/gokulcm",
  },
];
