import React from "react";
import "./team.scss";
import { ContentTeamData, MentorsData, DesignTeamData, WebTeamData } from "./data";
import TeamItem from "./TeamItem";

export default function Team() {
  return (
    <section id="team" class="team">
      <div class="container mentor-team">
        <div class="section-title" data-aos="fade-up">
          <h2>Mentoring Team</h2>
          <p>
            The Mentoring Team of four provides continuous support and guidance
            to our volunteers. They promote diversity of thought, tap into their
            existing knowledge, and direct the interns to a brighter future.
          </p>
        </div>

        <div class="members">
          {MentorsData.map((item, index) => (
            <TeamItem key={index} item={item} />
          ))}
        </div>
      </div>

      <div class="container content-team">
        <div class="section-title" data-aos="fade-up">
          <h2>Content Team</h2>
          <p>
            The Content Team of five interns is responsible for all the creative
            content generated by the Section, in the form of social media
            content, reports, proposals, etc. The team is mentored by Ms.
            Lekshmi Priya.
          </p>
        </div>

        <div class="members">
          {ContentTeamData.map((item, index) => (
            <TeamItem key={index} item={item} />
          ))}
        </div>
      </div>

      <div class="container design-team">
        <div class="section-title" data-aos="fade-up">
          <h2>Design Team</h2>
          <p>
            {" "}
            The Design Team of five interns executes all the designing works
            related to the Section, which include posters, flyers, etc. The team
            is mentored by Mr. Jacob Thomas, Treasurer, IEEE Kerala Young
            Professionals.
          </p>
        </div>

        <div class="members">
          {DesignTeamData.map((item, index) => (
            <TeamItem key={index} item={item} />
          ))}
        </div>
      </div>

      <div class="container web-team">
        <div class="section-title" data-aos="fade-up">
          <h2>Web Team</h2>
          <p>
            The Web Team of six interns handles the tasks related to IEEE Kerala
            Section’s official website, ieeekerala.org, and other such
            web-related activities of the Section. The team is mentored by Mr.
            Neeraj Ipe, Vice-Chair, IEEE Kerala Young Professionals.
          </p>
        </div>

        <div class="members">
          {WebTeamData.map((item, index) => (
            <TeamItem key={index} item={item} />
          ))}
        </div>
      </div>
    </section>
  );
}
